<a href="https://colab.research.google.com/github/tangannbelang/machineLearningTimedoor/blob/main/Python_for_data_science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python for data science lesson 2

In [ ]:
grocery_list = ['Bread','Cereal','Peanut Butter']
print(grocery_list)

['Bread', 'Cereal', 'Peanut Butter']


In [ ]:
print(grocery_list[0]) #Menampilkan data pertama
print(grocery_list[1]) #Menampilkan data kedua
print(grocery_list[-1]) #Menampilkan data terakhir

Bread
Cereal
Peanut Butter


In [ ]:
grocery_list.append('Sausage') #Menambahkan item pada list
grocery_list.append('Croissant')
grocery_list.remove('Bread') #Menghapus item pada list
print(grocery_list)

['Cereal', 'Peanut Butter', 'Sausage', 'Croissant']


In [ ]:
grocery_list[1] = 'Strawberry Jam' #Mengubah item indeks ke
print(grocery_list)
print(len(grocery_list)) #Menampilkan jumlah item pada list

['Cereal', 'Strawberry Jam', 'Sausage', 'Croissant']
4


In [ ]:
numbers = [130,100,140,150, 190, 200, 250,200,230,250] #Do It Yourself! Coba kamu isi dengan berat anggur yang dicatat oleh Jio.
print(numbers)

[130, 100, 140, 150, 190, 200, 250, 200, 230, 250]


In [ ]:
numbers.sort() #Mengurutkan item pada list menjadi urutan kecil ke besar.
print(numbers)

[100, 130, 140, 150, 190, 200, 200, 230, 250, 250]


In [ ]:
grade_3 = numbers[:4] #Mengambil item sebelum index ke 4
print(grade_3)
grade_2 = numbers[4:7] #Mengurutkan item pada list menjadi urutan kecil ke besar.
print(grade_2)
grade_1 = numbers[7:] #Mengambil item setelah index ke 7
print(grade_1)

[100, 130, 140, 150]
[190, 200, 200]
[230, 250, 250]


In [ ]:
products = ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Mouse', 'Printer']
products

['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Mouse', 'Printer']

In [ ]:
removed_product = products.pop(3)
print(f"Removed product: {removed_product}")
print(f"List after removal: {products}")

Removed product: Monitor
List after removal: ['Laptop', 'Mouse', 'Keyboard', 'Mouse', 'Printer']


In [ ]:
products.insert(2, 'Tablet')
print(f"List after adding 'Tablet': {products}")


List after adding 'Tablet': ['Laptop', 'Mouse', 'Tablet', 'Tablet', 'Keyboard', 'Scanner', 'Scanner', 'Mouse', 'Printer']


In [ ]:
removed_product = products.pop(3)
removed_product = products.pop(4)
products

['Laptop', 'Mouse', 'Tablet', 'Keyboard', 'Scanner', 'Mouse', 'Printer']

In [ ]:
products.insert(5, 'Scanner')
print(f"List after adding 'Scanner': {products}")

List after adding 'Scanner': ['Laptop', 'Mouse', 'Tablet', 'Keyboard', 'Scanner', 'Scanner', 'Mouse', 'Printer']


In [ ]:
temperature = [ #List terluar
    [25, 27, 28, 27], #Di dalamnya ada list lainnya.
    [23, 24, 26, 26],
    [24, 24, 27, 27],
    [22, 24, 25, 24]
]
temperature

[[25, 27, 28, 27], [23, 24, 26, 26], [24, 24, 27, 27], [22, 24, 25, 24]]

In [ ]:
print(temperature[0])
print(temperature[0][0])


[25, 27, 28, 27]
25


In [ ]:
temperature.append([23,24,24,26])
print(temperature)
print(len(temperature))

[[25, 27, 28, 27], [23, 24, 26, 26], [24, 24, 27, 27], [22, 24, 25, 24], [23, 24, 24, 26]]
5


In [ ]:
cart = ["apple", "banana", "milk", "bread"]
cart

['apple', 'banana', 'milk', 'bread']

In [ ]:
print(cart[2])
print(cart[3])
cart[1] ='orange'
cart

milk
bread


['apple', 'orange', 'milk', 'bread']

In [ ]:
nilai = [90,88,70,98,82,90]
nilai

[90, 88, 70, 98, 82, 90]

In [ ]:
nilai.insert(3, 85)
nilai

[90, 88, 70, 85, 98, 82, 90]

In [ ]:
nilai.count(90)

2

In [ ]:
nilai.pop(5)
nilai

[90, 88, 70, 85, 98, 90]

In [ ]:
hobi =[
    ['Mark', 12, 'Reading'],
    ['Joe', 16, 'Football'],
    ['Shabrina', 15, 'Cooking'],
    ['Aaron', 19, 'Coding']
    ]
hobi

[['Mark', 12, 'Reading'],
 ['Joe', 16, 'Football'],
 ['Shabrina', 15, 'Cooking'],
 ['Aaron', 19, 'Coding']]

In [ ]:
subjects =("Python","C++","Java Script")
print(subjects)
print(len(subjects))

('Python', 'C++', 'Java Script')
3


In [ ]:
print(subjects[-1])
print(subjects[1])
print(subjects[0:2])
print("Python" in subjects)
print("Java" in subjects)

Java Script
C++
('Python', 'C++')
True
False


In [ ]:
import random
friend_list = ['Brian','Cia','Petter','Drake']
random_name = random.choice(friend_list)
print(random_name)

Petter


In [ ]:
import random
import string
print('Welcome to Password Maker!')
adjectives_list = ["sleepy", "slow", "fluffy", "red", "yellow", "green", "blue"]
nouns_list = ["Dinosaur", "Ball", "Dragon","Hammer", "Apple", "Duck", "Panda"]

Welcome to Password Maker!


In [ ]:
#---------------------------------------------------
adjective = random.choice(adjectives_list)
noun = random.choice(nouns_list)
number = random.randrange(0, 100)
char = random.choice(string.punctuation)
#---------------------------------------------------
                         #2
#---------------------------------------------------
password = adjective + noun + str(number) + char
print('Recommended password: ' + password)

Recommended password: sleepyHammer87_


# Python for data science lesson 3

In [ ]:
movie = {
    'title': 'Jumanji : The Next Level',
    'year': 2017,
    'genre' :'Adventure',
}

In [ ]:
movie_2 = {
    'title': 'Frozen II',
    'year': 2019,
    'genre' :'Family',
}

In [ ]:
print(movie['title'])
print(movie['year'])

Jumanji : The Next Level
2017


In [ ]:
movie.update({'viewers': 44324578}) #Menambahkan item baru
movie["genre"] = "Adventure/Comedy" #Mengganti value dari key genre
del movie['year'] #Menghapus item years

print(movie)

{'title': 'Jumanji : The Next Level', 'genre': 'Adventure/Comedy', 'viewers': 44324578}


In [ ]:
movie_2.update({'viewers': 98698637}) #Menambahkan item baru
movie_2["genre"] = "Family/Musical" #Mengganti value dari key genre
print(movie_2)

{'title': 'Frozen II', 'year': 2019, 'genre': 'Family/Musical', 'viewers': 98698637}


# Python for data science lesson 4

In [ ]:
friends_list = ['Amanda', 'Bruno', 'Camila', 'Drake', 'Elvis', 'Freddie','George','Harry','Iggy','Joji']


In [ ]:
for i in friends_list: #nama list
    print(i) #Kode yang ingin diulang harus menjorok

Amanda
Bruno
Camila
Drake
Elvis
Freddie
George
Harry
Iggy
Joji


In [ ]:
for i in range(3):
    print(friends_list[i])

Amanda
Bruno
Camila


In [ ]:
for i in range(1,11,2): # start dari 1, end di 11 & Increment, yang artinya : I  = i+2 (Nomor Terakhir)
    print(friends_list[i])

Bruno
Drake
Freddie
Harry
Joji


In [ ]:
for i in range(1, 5):
   print(f"Lap {i}, Track 1")
   print(f"Lap {i}, Track 2")
   print(f"Lap {i}, Track 3")
   print(f"Lap {i}, Track 4")

Lap 1, Track 1
Lap 1, Track 2
Lap 1, Track 3
Lap 1, Track 4
Lap 2, Track 1
Lap 2, Track 2
Lap 2, Track 3
Lap 2, Track 4
Lap 3, Track 1
Lap 3, Track 2
Lap 3, Track 3
Lap 3, Track 4
Lap 4, Track 1
Lap 4, Track 2
Lap 4, Track 3
Lap 4, Track 4


In [ ]:
fruits = ['banana', 'apple', 'mango']
names = ['Alice', 'Bob', 'Charlie']

In [ ]:
for fruit in fruits:
   for name in names:
       print(f"{name} likes {fruit}")

Alice likes banana
Bob likes banana
Charlie likes banana
Alice likes apple
Bob likes apple
Charlie likes apple
Alice likes mango
Bob likes mango
Charlie likes mango


In [ ]:
for i in range(1, 6):
   for j in range(1, i+1):
       print("*", end=" ")
   print()

* 
* * 
* * * 
* * * * 
* * * * * 


In [ ]:
movie = {
   'title': 'The Dark Knight',
   'director': 'Christopher Nolan',
   'year': 2008
}
print(movie['title'])
print(movie['director'])
print(movie['year'])

The Dark Knight
Christopher Nolan
2008


In [ ]:
for key in movie:
   print(key, movie[key])


title The Dark Knight
director Christopher Nolan
year 2008


In [ ]:
n=3
for n in range(100):
  print (n)
  n+=3

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [ ]:
i = 1
while i <= 10:
   print("*" * i)
   i += 1

*
**
***
****
*****
******
*******
********
*********
**********


In [ ]:
friends = ['Alice', 'Bob', 'Charlie', 'David']
i = 0
while i < len(friends):
   print("Hello, " + friends[i])
   i += 1

Hello, Alice
Hello, Bob
Hello, Charlie
Hello, David


In [ ]:
for i in range(5):
   while i < 5:
       print(i, end=" ") # print number horizontally
       i += 1 # increment the i number
   print() # create enter

0 1 2 3 4 
1 2 3 4 
2 3 4 
3 4 
4 


In [ ]:
# Inisialisasi variabel
saving = 0
week = 0


while saving < 100:
   saving += 10
   week +=1


# Menampilkan hasil
print("Ali needs ", week, " weeks to collect $100.")

Ali needs  10  weeks to collect $100.


In [ ]:
import random
# The computer selects a random number between 1 and 10
secret_number = random.randint(1, 10)

In [ ]:
# Initialize the guess
guess = None
# Loop to ask for guesses from the user until correct
while True:
   guess = int(input("Guess a number between 1 and 10: "))
   if (guess == secret_number):
    print("Congratulations Your guess is correct.")
    break

Guess a number between 1 and 10: 7
Congratulations Your guess is correct.


# Lesson 5

In [ ]:
allowance = 10
spending = 8
print(allowance < spending)
print(allowance > spending)
print(allowance != spending)
print(allowance == spending)

False
True
True
False


In [ ]:
print((allowance == 10) and (spending == 8)) #True
print((allowance == 12) or (spending == 8)) #True

True
True


In [ ]:
students_name = ['Alex','Bryan','Christ','Dave','Eva']
students_score = [100,75,80,78,99]
students_grade = []

In [ ]:
for i in students_score:
    if ( i >= 90):
        students_grade.append('A') # Menambahkan nilai pada list.
    elif(i >= 70):
        students_grade.append('B')
    else:
        students_grade.append('C')
print(students_grade)

['A', 'B', 'B', 'B', 'A']


In [ ]:
age = input("Enter your age: ")


Enter your age: 23


In [ ]:
# isnumeric() method checks whether the string consists of only numeric characters.
if age.isnumeric() and int(age) < 18:
   print("You are still underage.")
elif age.isnumeric() and int(age) >= 18 and int(age) < 65:
   print("You are an adult.")
elif age.isnumeric() and int(age) >= 65:
   print("You are a senior citizen.")
else:
   print("Invalid input.")

You are an adult.


# Lesson 6


In [ ]:
number = [10, 16, 30, 21]
print(max(number)) #menampilkan nilai yang paling besar
print(min(number)) #menampilkan nilai yang paling kecil
print("hello".upper()) #Mengubah teks menjadi huruf Kapital
print("WELCOME".lower()) #Mengubah teks menjadi huruf kecil

30
10
HELLO
welcome


In [ ]:
def order_pizza(): #Membuat function diawali dengan def lalu nama function
    quantity = 7
    price = 10
    total_order = quantity * price
    print(f"Total order  $:  {total_order}" )

In [ ]:
order_pizza() #Menjalankan function.


Total order  $:  70


In [ ]:
def order_pizza2(): #Membuat function diawali dengan def lalu nama function
    quantity = int(input('Quantity order'))
    price = 10
    total_order = quantity * price
    print(f"Total order  $:  {total_order}" )

In [ ]:
order_pizza2()

Quantity order9
Total order  $:  90


In [ ]:
total = 50 #Global variable : variable di deklarasikan diluar function.
def sum():
    first = 10
    second = 20
    total = first+second
    print(total)
print(total)
sum()

50
30


# Lesson 7 OOP


In [ ]:
class Laptop:
    def __init__(self, brand, release_year, color,RAM):
        self.laptop_brand = brand
        self.laptop_release_year = release_year
        self.laptop_color = color
        self.laptop_RAM = RAM
    def information(self):
        return f"{self.laptop_color} Laptop {self.laptop_brand} release in {self.laptop_release_year} with {self.laptop_RAM} RAM"

In [ ]:
#indentasi sejajar dengan class
laptop_1 = Laptop("Dell", 2021, "Grey", 8)

In [ ]:
#indentasi sejajar dengan class
laptop_2 = Laptop("Macbook", 2022, "Silver", 8)

In [ ]:
print(laptop_1.laptop_brand)
# Tambahkan code di bawah ini
print(laptop_1.information())

Dell
Grey Laptop Dell release in 2021 with 8 RAM


# Lesson 9

In [ ]:
grades = [100,98,97,93,91,90,88,85,80,78]

In [ ]:
def bubble_sort(arr):
   n = len(arr)
   for i in range(n):
       for j in range(0, n-i-1):
           if arr[j] < arr[j+1]:
               arr[j], arr[j+1] = arr[j+1], arr[j]
       print(arr)
   return arr

In [ ]:
sorted_grades = bubble_sort(grades)
print(sorted_grades)

[100, 98, 97, 93, 91, 90, 88, 85, 80, 78]
[100, 98, 97, 93, 91, 90, 88, 85, 80, 78]
[100, 98, 97, 93, 91, 90, 88, 85, 80, 78]
[100, 98, 97, 93, 91, 90, 88, 85, 80, 78]
[100, 98, 97, 93, 91, 90, 88, 85, 80, 78]
[100, 98, 97, 93, 91, 90, 88, 85, 80, 78]
[100, 98, 97, 93, 91, 90, 88, 85, 80, 78]
[100, 98, 97, 93, 91, 90, 88, 85, 80, 78]
[100, 98, 97, 93, 91, 90, 88, 85, 80, 78]
[100, 98, 97, 93, 91, 90, 88, 85, 80, 78]
[100, 98, 97, 93, 91, 90, 88, 85, 80, 78]


In [ ]:
def insertion_sort(arr):
   n = len(arr)
   for i in range(1, n):
       key = arr[i]
       j = i-1
       while j >= 0 and key > arr[j]:
           arr[j+1] = arr[j]
           j -= 1
       arr[j+1] = key
       print(arr)
   return arr

In [ ]:
insertion_sort(grades)

[100, 98, 97, 93, 91, 90, 88, 85, 80, 78]
[100, 98, 97, 93, 91, 90, 88, 85, 80, 78]
[100, 98, 97, 93, 91, 90, 88, 85, 80, 78]
[100, 98, 97, 93, 91, 90, 88, 85, 80, 78]
[100, 98, 97, 93, 91, 90, 88, 85, 80, 78]
[100, 98, 97, 93, 91, 90, 88, 85, 80, 78]
[100, 98, 97, 93, 91, 90, 88, 85, 80, 78]
[100, 98, 97, 93, 91, 90, 88, 85, 80, 78]
[100, 98, 97, 93, 91, 90, 88, 85, 80, 78]


[100, 98, 97, 93, 91, 90, 88, 85, 80, 78]

In [ ]:
def linear_search(arr, target):
   for i in range(len(arr)):
       if arr[i] == target:
           return i
   return "Target not found in the list"

In [ ]:
grades.sort(reverse=True) # sorting the list in descending order
print(grades)
# call the function
index = linear_search(grades, 97)
print("Target number found at index: ", index)

[100, 98, 97, 93, 91, 90, 88, 85, 80, 78]
Target number found at index:  2


# Lesson 10

In [ ]:
import numpy as np


In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])


In [ ]:
print(a*b)


[ 6 14 24 36 50]


In [ ]:
print(a) # Menampilkan output dari Numpy array yang sudah dibuat
print(b) # Menampilkan output dari Numpy array yang sudah dibuat

[1 2 3 4 5]
[ 6  7  8  9 10]


In [ ]:
c= np.array(['arief', 'd', 1,2])

In [ ]:
print(c)

['arief' 'd' '1' '2']


In [ ]:
Array2D = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])


In [ ]:
Array2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
array3D = np.array([[[1,2,3], [4,5,6]],
[[7,8,9], [10,11,12]],
[[13,14,15], [16,17,18]]])

In [ ]:
array3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [ ]:
data = np.array([[1,2,3,4], [5,6,7,8]])
print(data.shape)
print(data[0, 3])

(2, 4)
4


In [ ]:
# Tambahkan code di bawah ini
print(data[:, 2])
print(data[1, :])

[3 7]
[5 6 7 8]


In [ ]:
print(data[:, 1:3])
print(data[1, 1:4])

[[2 3]
 [6 7]]
[6 7 8]


In [ ]:
print(data.diagonal(2))


[3 8]


In [ ]:
data

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
empty = np.zeros((4,4), dtype="int")
print(empty)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
empty[0, 1:4] = [1,55,3]
print(empty)

[[ 0  1 55  3]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]]


In [ ]:
empty[-1, 0] = 7 #-1 = row index terakhir
print(empty) # ^
             # | nilai baru

[[ 0  1 55  3]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 7  0  0  0]]


In [ ]:
empty[1:3, 1] = [9,5]
print(empty)   # ^
               # | Nilai baru

[[ 0  1 55  3]
 [ 0  9  0  0]
 [ 0  5  0  0]
 [ 7  0  0  0]]


In [ ]:
c = np.array([3,6,9,12])
d = np.array([2,4,6,8])
print(np.add(c,d))
print(np.subtract(c,d))
print(np.multiply(c,d))
print(np.divide(c,d))

[ 5 10 15 20]
[1 2 3 4]
[ 6 24 54 96]
[1.5 1.5 1.5 1.5]


In [ ]:
print(c.sum(), d.sum())
print(c.min(), d.min())
print(c.max(), d.max())

30 20
3 2
12 8


In [ ]:
import random
board = np.zeros((3, 3)).astype(int)
turn = 1
move = 9

In [ ]:
board

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [41]:
while move >0:
    # Draw the board
#         a
#----------------------
    print (board)
    play_turn()
#----------------------
    if check_win():
#         b
#--------------------------------------------
        print (f"Player {turn} has won!")
        break
#--------------------------------------------
#         c
#--------------------------------------------
    turn = turn*-1
    move = move -1
#--------------------------------------------

[[0 0 0]
 [0 0 0]
 [0 0 0]]


KeyboardInterrupt: Interrupted by user

In [42]:
def check_win():
    if any(np.sum(board, 1)==3) or any(np.sum(board, 0)==3) or sum(np.diag(board))==3 or sum(np.diag(board[::-1]))==3:
        return True
    if any(np.sum(board, 1)==-3) or any(np.sum(board, 0)==-3) or sum(np.diag(board))==-3 or sum(np.diag(board[::-1]))==-3:
        return True
    return False

In [ ]:
def play_turn():
    if(turn ==1):
        x = int(input(f"What is player {turn}'s x position?")) # kode akan dijelaskan dibawah
        y = int(input(f"What is player {turn}'s y position?")) # dalam bagian (a)
    else:
        x = random.randint(0,2); # kode akan dijelaskan dibawah
        y = random.randint(0,2); # dalam bagian (b)

# Lesson 11

In [43]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("ammaraahmad/us-ecommerce-record-2020")

print("Path to dataset files:", path)

100%|██████████| 160k/160k [00:00<00:00, 658kB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/ammaraahmad/us-ecommerce-record-2020/versions/1


In [44]:
import pandas as pd #Import Pandas dengan alias pd
data = [1,2,3]
df = pd.DataFrame(data) #Mengubah list menjadi dataframe
df

0
0  1
1  2
2  3

In [45]:
student = [['Tom', 90], ['Jack', 80], ['Jill', 70]] #Buat 2D list untuk 2 Column
data_student = pd.DataFrame(student, columns=['Name', 'Grade']) #'Name' , 'Grade' Adalah Column header
data_student

Name  Grade
0   Tom     90
1  Jack     80
2  Jill     70

In [46]:
data_student['Name']


0     Tom
1    Jack
2    Jill
Name: Name, dtype: object

In [47]:
new_student = [['Sam', 60], ['Mary', 50], ['John', 40], ['Joseph', 30]]
new_student = pd.DataFrame(new_student, columns=['Name', 'Grade'])
data_student = pd.concat([data_student, new_student], ignore_index=True)#menggabungkan 2 dataframe
data_student

Name  Grade
0     Tom     90
1    Jack     80
2    Jill     70
3     Sam     60
4    Mary     50
5    John     40
6  Joseph     30

In [48]:
data_student.head(3)


Name  Grade
0   Tom     90
1  Jack     80
2  Jill     70

In [49]:
data_student.tail(3)


Name  Grade
4    Mary     50
5    John     40
6  Joseph     30

In [50]:
data_student.to_csv('data_student.csv')
